name: Generate README Index

on:
  push:
    branches:
      - main # or master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: You must explicitly grant write permission for this to work
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Markdown Index
        uses: DaanV2/Markdown-Action-Create-Indexes@v3.0.0
        with:
          folder: ${{github.workspace}}
          filename: README.md
          include: |
            *.md
            *.pdf
            *.mobi
            *.epub
            *.zip

      - name: Commit and Push Changes # <--- UPDATED STEP
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Auto-update: Generate folder/file index in README"
          # By default, this action commits all changes, 
          # but you can specify a glob pattern if needed:
          # files: 'README.md'
