name: Generate README Index

on:
  push:
    branches:
      - main # or master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: You must explicitly grant write permission for this to work
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Markdown Index
        uses: DaanV2/Markdown-Action-Create-Indexes@v3.0.0
        with:
          folder: ${{github.workspace}}
          filename: Index.md
     
      - name: Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "Bot@Example.com"
          git config --global user.name "DaanV2 Bot"
          git add .
          git commit -m "auto: Generated markdown indexes"
          git push
      
